common/Cargo.toml, common/src/errors.rs, fri/Cargo.toml, fri/src/verifier/errors.rs, math/Cargo.toml, math/src/errors.rs
This PR removes dependency on `thiserror` and `displaydoc` crates. The primary motivation is to reduce use of std-based dependencies and the number of dependences overall.
=> Dependency clean-up

common/src/proof.rs, crypto/src/merkle/proofs.rs, examples/src/main.rs, math/src/errors.rs, verifier/src/channel.rs
This PR addresses #6 and also improves queries serialization/deserialization overall. Specifically:
The overall impact of this PR is ~1% reduction in proof sizes, but it also lays groundwork for switching over to new Merkle tree implementation.
=> Queries serialization improvements

common/src/errors.rs, fri/src/errors.rs, fri/src/lib.rs, fri/src/proof.rs, fri/src/prover/monolith/mod.rs, fri/src/prover/monolith/tests.rs, fri/src/prover/tests.rs, fri/src/verifier/channel.rs, fri/src/verifier/mod.rs, verifier/src/channel.rs
This PR refactors FRI proof serialization/deserialization to be more in-line with main proof serialization. This is similar to #5, however, we cannot use `Queries` struct directly in FRI because the structures are slightly different.
The impact of this PR is further reduction of proof size by ~3% (in addition to the reduction from #15). It also lays groundwork in the FRI module for migration to the new Merkle tree implementation.
=> Fri proof serialization improvements

prover/src/monolith/constraints/evaluation_table.rs
This PR implements point-wise application of constraint divisors during constraint polynomial composition. The advantages of point-wise division are:
- It is fully parallelizable (and trivially distributable).
- It is actually 2x - 3x faster that previous implementation which used synthetic division. Though, the impact on the overall proof generation is negligible since constraint composition was very fast to begin with.
- It lays groundwork for improved constraint evaluation methodology which should result in significant speedup, once implemented.
This PR affects only prover code as verifier code use a different methodology for applying constraint divisors.
=> [prover] Point-wise division

common/src/air/boundary/mod.rs, common/src/air/divisor.rs, common/src/air/mod.rs, crypto/src/random/mod.rs, fri/src/folding/quartic/concurrent.rs, fri/src/folding/quartic/mod.rs, fri/src/prover/channel.rs, fri/src/prover/monolith/mod.rs, fri/src/verifier/context.rs, fri/src/verifier/mod.rs, math/src/fft/concurrent.rs, math/src/fft/mod.rs, math/src/fft/serial.rs, math/src/field/extensions/quadratic.rs, math/src/field/f128/mod.rs, math/src/field/f62/mod.rs, math/src/field/traits.rs, prover/src/channel.rs, prover/src/monolith/composer/mod.rs, prover/src/monolith/constraints/boundary.rs, prover/src/monolith/constraints/composition_poly.rs, prover/src/monolith/constraints/evaluation_table.rs, prover/src/monolith/constraints/evaluator.rs, prover/src/monolith/mod.rs, prover/src/monolith/trace/poly_table.rs, verifier/src/channel.rs, verifier/src/evaluator.rs, verifier/src/lib.rs
This PR implements tighter bounds for field types. Specifically, instead of passing field elements as: `<B: StarkField, E: FieldElement + From<B>>`, we now say `<B: StarkField, E: FieldElement<BaseField = B>>`.
=> Field trait improvements

math/src/field/f128/mod.rs, math/src/field/f62/mod.rs, math/src/field/traits.rs, prover/src/monolith/mod.rs, verifier/src/lib.rs
This PR implements a new way to specify extension fields for a given base field. Basically, `StarkField` trait now exposes a type called `QuadExtension` which can be used to describe quadratic extension of a specific `StarkField`. This approach is more flexibly and should make addressing #12 easier.
=> Extension field specifier

README.md, common/Cargo.toml, common/src/options.rs, common/src/proof/commitments.rs, common/src/proof/context.rs, common/src/proof/mod.rs, common/src/proof/ood_frame.rs, common/src/proof/queries.rs, crypto/Cargo.toml, examples/Cargo.toml, examples/src/lamport/signature.rs, examples/src/main.rs, fri/Cargo.toml, fri/src/errors.rs, fri/src/proof.rs, fri/src/prover/tests.rs, math/Cargo.toml, math/src/field/f128/mod.rs, utils/src/errors.rs, utils/src/lib.rs, utils/src/tests.rs
This PR addresses #7 but since a few other PRs already implemented the bulk of proof serialization optimizations (e.g. #15 and #16), the actual impact of this PR on proof size is negligible.
However, it does allow us to get rid of `serde` dependencies reducing total number of direct external dependencies to 5: `blake3`, `sha3`, `log` (for prover only), `rayon` (for concurrent prover only), `rand` (not really needed).
=> Custom proof serialization

math/src/field/traits.rs
I did not see any mention of MSRV, and the project fails to compile in stable 1.51.0 with the following error
> error[E0391]: cycle detected when computing the supertraits of `field::traits::FieldElement`
--> math/src/field/traits.rs:27:1
|
27  | / pub trait FieldElement:
28  | |     Copy
29  | |     + Clone
30  | |     + Debug
...   |
185 | |     fn prng_vector(seed: [u8; 32], n: usize) -> Vec<Self>;
186 | | }
| |_^
|
= note: ...which again requires computing the supertraits of `field::traits::FieldElement`, completing the cycle
note: cycle used when collecting item types in module `field::traits`
--> math/src/field/traits.rs:27:1
|
27  | / pub trait FieldElement:
28  | |     Copy
29  | |     + Clone
30  | |     + Debug
...   |
185 | |     fn prng_vector(seed: [u8; 32], n: usize) -> …
=> Fix wrong positive of E0391 (cycle error) for FieldElement trait in toolchains < 1.52.0

crypto/Cargo.toml, crypto/src/hash/mod.rs, examples/Cargo.toml
This PR brings the following dependencies up to date:
- `blake3` to 1.0
- `env_logger` to 0.9
=> Dependency updates

air/src/proof/queries.rs, crypto/src/hash/mod.rs, math/src/field/extensions/quadratic.rs, math/src/field/f128/mod.rs, math/src/field/f62/mod.rs, math/src/field/traits.rs
This PR introduces a concept of malleable field elements - i.e., elements which might have redundant internal representation for the same canonical representation. For example, this is the case for field elements where internally elements are stored in the range `[0, 2M)` (rather than `[0, M)`) which we use for our `f62` field (the `f128` field does not have this issue because we don't use Montgomery arithmetic for it).
This also allows us to hash elements consistently by first normalizing their internal representation, and only then hashing them. We do this for malleable elements only, since non-malleable elements don't need to be normalized, and thus, we can hash them directly.
We also make sure that we always write elements into the proof in canonical representation. This avoids issues …
=> Malleable field elements

air/src/proof/commitments.rs, crypto/README.md, crypto/benches/hash.rs, crypto/src/hash/blake/mod.rs, crypto/src/hash/blake/tests.rs, crypto/src/hash/mod.rs, crypto/src/hash/rescue/mod.rs, crypto/src/hash/rescue/rp62_248.rs, crypto/src/hash/rescue/rp62_248/digest.rs, crypto/src/hash/rescue/rp62_248/mod.rs, crypto/src/hash/rescue/rp62_248/tests.rs, crypto/src/hash/sha/mod.rs, crypto/src/lib.rs, crypto/src/merkle/tests.rs, crypto/src/random/mod.rs, examples/src/merkle/mod.rs, examples/src/utils/rescue.rs, math/src/field/extensions/quadratic.rs, math/src/field/f128/mod.rs, math/src/field/f128/tests.rs, math/src/field/f62/mod.rs, math/src/field/f62/tests.rs, math/src/field/traits.rs, utils/src/lib.rs
This PR will implement high-performance instantiation of Rescue Prime hash function as described in #36
=> Rescue prime

.github/workflows/publish.yml, CHANGELOG.md, README.md, air/Cargo.toml, crypto/Cargo.toml, examples/Cargo.toml, fri/Cargo.toml, math/Cargo.toml, prover/Cargo.toml, utils/core/Cargo.toml, utils/rand/Cargo.toml, verifier/Cargo.toml, winterfell/Cargo.toml
This PR prepares all crates for publishing v0.2 version of all crates to crates.io
=> Preparation for publishing v0.2 to crates.io

crypto/src/random/mod.rs, fri/src/proof.rs
There are currently two issues when proving with field extensions:
- the first one, rather minor, is when sampling from the public coin. It may happen for cubic extension that we run out of trials by lack of luck. Increasing the number of mentioned trials before outputting an error solved this.
- the second one is with respect to the cubic extension. Currently, FriProof serialization is expecting a power-of-two remainder length, which is not the case when proving in the cubic extension. The second commit fixes this.
Both errors are visible on my temporary branch https://github.com/Nashtare/winterfell/tree/f62-example where I added an example of Fibonacci with `f62`, followed by the two fixes above (go back in the history when running `./target/release/winterfell -e 3 fib-f62` to see the …
=> Fix cubic extension

air/src/air/transition/mod.rs, air/src/proof/context.rs, crypto/src/hash/rescue/rp62_248/mod.rs, crypto/src/hash/rescue/rp64_256/mod.rs, fri/src/folding/mod.rs, fri/src/prover/mod.rs, fri/src/verifier/mod.rs, math/src/field/f128/mod.rs, math/src/field/f62/mod.rs, math/src/field/f64/mod.rs, math/src/field/traits.rs
I didn't attach it to the last PR (and I'm not sure it deserves a PR honestly) but here are some typo fixes, mostly from `winter_math`.
There is a similar typo in the Changelog (`filed` -> `field`) but I didn't touch it, as I wasn't sure if I could change previous entries of the Changelog.
=> Fix some typos

CHANGELOG.md, crypto/Cargo.toml, crypto/README.md, crypto/src/hash/rescue/rp64_256/digest.rs, crypto/src/hash/rescue/rp64_256/mod.rs, crypto/src/hash/rescue/rp64_256/tests.rs
This PR makes a few minor updates to Rp64_256 hash function implementation:
* Implemented digest to array conversion for Rp64_256 digest.
* Makes `apply_permutation()` and `apply_round()` functions public.
=> Rp64_256 improvements

math/benches/fft.rs, math/src/fft/serial.rs, math/src/field/extensions/cubic.rs, math/src/field/extensions/mod.rs, math/src/field/extensions/quadratic.rs, math/src/field/f128/mod.rs, math/src/field/f128/tests.rs, math/src/field/f62/mod.rs, math/src/field/f62/tests.rs, math/src/field/f64/mod.rs, math/src/field/f64/tests.rs, math/src/field/mod.rs, math/src/field/traits.rs, math/src/lib.rs
This PR implements `ExtensionOf` trait in the `math` crate. This trait provides a way to multiply an extension field element by a base field element directly (without going through conversion from base field to extension field first). The net result of this is that multiplications of base and extension field elements become much faster. Specifically, for FFT-based polynomial evaluation, when polynomial coefficients are in the extension field, we get about 15% speedup vs. the previous implementation.
=> ExtensionOf trait

CHANGELOG.md, README.md, air/Cargo.toml, crypto/Cargo.toml, examples/Cargo.toml, fri/Cargo.toml, math/Cargo.toml, prover/Cargo.toml, utils/core/Cargo.toml, utils/rand/Cargo.toml, verifier/Cargo.toml, winterfell/Cargo.toml
This PR prepares the library for v0.4 release.
=> v0.4 release prep

air/src/air/context.rs
This (tiny) PR increases the transition constraint exemption limit in `AirContext` by one.
I believe that in some cases, the current limit may be a problem (for instance a trace where the 2^k rows are necessary, which then needs to be extended to the next power of two 2^{k+1}). In such cases, the current limit won't be sufficient, because the last evaluation frame to be checked on the proving side will overlap between the actual trace and the dummy values.
=> Enlarge exemption limit

math/benches/field.rs, math/src/field/extensions/cubic.rs, math/src/field/extensions/quadratic.rs, math/src/field/f62/mod.rs, math/src/field/f64/mod.rs
This PR overrides the default `double()` method of the `FieldElement` trait for `f64`, `f62`, and related extensions. 
This yielded on my machine a speed-up of respectively 22.1% / 37.9% / 27.5% for `f64` simple/quad/cube and 7.3% / 7.2% / 4.2% for `f62` simple/quad/cube.
I haven't found a significant improvement on `f128` hence I left it untouched. I also added the `double()` operation to the field benchmarks for comparison with the `add` methods.
=> Custom doubling

prover/src/matrix.rs
Instead of cloning the entire matrix with a single .clone(), which will clone each column vector sequentially, do each column clone
inside the parallelized loop. This has a significant performance impact when run with concurrency.
Running the [stark-bench](https://github.com/bobbinth/stark-bench) benchmarks on a 64-core AWS machine (c7g.16xlarge) leads to a ~57% improvement in the interpolation step. UPDATE: The parameters I used to obtain this result were `stark-bench -c 255 -n 23 -b 2`.
=> Performance improvement in Matrix::interpolate_columns

crypto/src/errors.rs, crypto/src/hash/sha/mod.rs, crypto/src/merkle/proofs.rs, crypto/src/merkle/tests.rs
This PR proposes an implementation of a `into_paths` method for `BatchMerkleProof`.
This method takes a batch proof and outputs the individual Merkle path proofs.
=> Merkle path unbatch

CHANGELOG.md, air/Cargo.toml, air/src/air/trace_info.rs, crypto/Cargo.toml, crypto/src/random/mod.rs, examples/Cargo.toml, examples/src/rescue_raps/custom_trace_table.rs, examples/src/rescue_raps/mod.rs, fri/Cargo.toml, math/Cargo.toml, math/src/field/f64/mod.rs, prover/Cargo.toml, prover/src/trace/trace_table.rs, utils/core/Cargo.toml, utils/core/src/lib.rs, utils/rand/Cargo.toml, verifier/Cargo.toml, winterfell/Cargo.toml
This PR updates versions of all crates to v0.4.1 in preparation of v0.4.1 release. Changelog has also been updated to reflect all changes since v0.4 release.
=> Update versions of all crates to v0.4.1

prover/src/lib.rs
This PR adds logging to print out auxiliary trace segment construction time.
=> Add logging for aux trace segment construction

crypto/src/merkle/proofs.rs
Modifying the visibility for members of the `BatchMerkleProof` struct. Found that this was needed in another application of the crypto crate.
=> Changed visibility of members for batched merkle proof

CHANGELOG.md, air/Cargo.toml, crypto/Cargo.toml, examples/Cargo.toml, fri/Cargo.toml, math/Cargo.toml, prover/Cargo.toml, utils/core/Cargo.toml, utils/rand/Cargo.toml, verifier/Cargo.toml, winterfell/Cargo.toml
This PR updates versions of all crates to v0.4.2 in preparation for v0.4.2 release.
=> Update crate version to v0.4.2

math/src/field/f64/mod.rs
Correction of a mistake in the documentation related to Montgomery representation.
=> Correction of docs for f64 field

math/src/field/f64/mod.rs
This PR proposes a simpler method to convert a field element in Montgomery form to canonical form. The current method uses Montgomery reduction where the input is expected to be u128 (i.e. the result of a multiplication). Since we know that field elements are stored as u64, we can use a simpler method to compute $\frac{x}{2^{64}}\textit{ mod }p$.
=> Simpler Montgomery reduction for u64

prover/src/constraints/evaluator.rs
This fix addresses #96 and [0xPolygonMiden/miden-vm/#602](https://github.com/0xPolygonMiden/miden-vm/issues/602). I've summarized the fix [here](https://github.com/0xPolygonMiden/miden-vm/issues/602#issuecomment-1370845674).
=> Concurrent Execution Panic Fix

math/src/fft/fft_inputs.rs, math/src/fft/mod.rs, math/src/fft/serial.rs, math/src/fft/tests.rs
This PR partly addresses #93. It introduces a `FftInput` trait in the `maths` crate, which defines the shape of the input for the FFT computation. This trait is implemented on `[E]`in this PR.
=> New FftInputs trait

.github/workflows/ci.yml, math/src/fft/concurrent.rs, math/src/fft/fft_inputs.rs
This PR fixes build with `concurrent` feature.
@irakliyk I have included a new CI job checking that we can build with all features activated, to prevent this kind of issue happening in the future. It is only checking the compilation, should it run tests as well instead?
closes #131
=> Fix concurrent fft

fri/src/verifier/mod.rs, math/src/field/traits.rs, verifier/src/composer.rs, verifier/src/evaluator.rs, verifier/src/lib.rs
Add `exp_vartime` method to the `FieldElement` trait to speed-up verifier exponentiations.
This is currently useful only for `f64` which implements by default constant-time operations (`exp_vartime` there is about 40% faster than its constant-time counterpart), but could be useful if we were to implement constant-time operations by default for all other supported fields.
For the fib-small example over f64, the verifier speed-up is measured at around 8% on my machine.
=> Add exp_vartime method for FieldElement trait

math/src/field/extensions/cubic.rs, math/src/field/extensions/quadratic.rs, math/src/field/f64/mod.rs, math/src/field/f64/tests.rs, math/src/field/traits.rs
This PR implements more optimized methods for computing squares in the degrees 2 and 3 extension fields. This is in contrast to the old way of squaring which was using a generic multiplication.
Also included, is a method for multiplying field elements in 64-bit field with constants smaller than $2^{32}$. This will be useful for extension fields that are defined by irreducible polynomials of the form $X^d - \omega$ where $d$ is the degree of the extension and $\omega$ is a field element. In the case of such extension fields, reduction modulo $X^d - \omega$ becomes just a multiplication by $\omega$ and thus a method for multiplying with small constants will be useful.
=> Optimized methods for squaring in extension fields of degree 2 & 3

math/src/field/extensions/cubic.rs, math/src/field/extensions/quadratic.rs, math/src/field/f64/mod.rs
This PR adds convenience methods to convert quadratic and cubic extension field elements into corresponding arrays of base field elements.
=> Conversion to base elements for extension field elements

prover/src/trace/trace_table.rs
Currently, `TraceTable::fill()` uses `Fn` as the closure type for both its closure arguments. This needlessly restricts the possibilities for the caller. This PR uses the least restrictive closure type for each argument. 
For example, the following is now made possible:
```rust
pub fn build_do_work_trace(start: BaseElement, n: usize) -> TraceTable<BaseElement> {
let trace_width = 1;
let mut trace = TraceTable::new(trace_width, n);
let mut gen = Generator{};
trace.fill(
|state| {
state[0] = start;
},
|_, state| {
// here, `gen` is borrowed mutably by the closure,
// which is now allowed.
state[0] = state[0].exp(3u32.into()) + gen.next();
},
);
trace
}
struct Generator;
impl Generator {
fn next(&mut self) -> BaseElement { ... }
}
```
=> `TraceTable::fill()`: use least restrictive closure type for arguments

math/src/field/f64/mod.rs, math/src/field/f64/tests.rs
This change fixes the non-canonical conversion of 0 from its Montgomery form equivalent in `f64.`
closes #145
=> Fix as_int() non-canonical output

CHANGELOG.md, air/Cargo.toml, crypto/Cargo.toml, examples/Cargo.toml, fri/Cargo.toml, math/Cargo.toml, prover/Cargo.toml, utils/core/Cargo.toml, utils/rand/Cargo.toml, verifier/Cargo.toml, winterfell/Cargo.toml
This PR prepares the crates for v0.5 release. Specifically:
- Updates versions of all crates to v0.5.
- Updates versions of outdated dependences (there were a couple).
- Updates minimum required Rust version to v1.67.
- Updates the CHANGELOG.
=> Prepare v0.5 release

crypto/src/hash/mds/mds_f64_12x12.rs, crypto/src/hash/mds/mds_f64_8x8.rs, crypto/src/hash/rescue/rp62_248/mod.rs
Fixes a few typos and adds the first row describing the used MDS Matrices in their doc for completeness.
=> nit: Typos and doc

math/src/fft/fft_inputs.rs, math/src/fft/mod.rs, prover/Cargo.toml, prover/benches/row_matrix.rs, prover/src/domain.rs, prover/src/lib.rs, prover/src/matrix/col_matrix.rs, prover/src/matrix/mod.rs, prover/src/matrix/row_matrix.rs, prover/src/matrix/segments.rs, prover/src/matrix/tests.rs
This Pull Request is a continuation of #124 and partially addresses #93. It introduces a new matrix structure in the `matrix` module of the `prover` crate, which uses a row-major layout.
The following improvements have been made in this PR:
-  Introduction of a [Segment](https://github.com/0xKanekiKen/winterfell/blob/new-rowmatrix/prover/src/matrix/row_matrix.rs#L121-L127) struct that is utilized in processing a `column-major` matrix containing polynomial coefficients. to be evaluated on a larger domain. See [from_polys](https://github.com/0xKanekiKen/winterfell/blob/new-rowmatrix/prover/src/matrix/row_matrix.rs#L380-L428).
-  The new structure provides improved efficiency in NTT computation. The [RowMatrix](https://github.com/0xKanekiKen/winterfell/blob/new-rowmatrix/prover/src/matrix/row …
=> Rowmatrix for NTT

air/src/air/coefficients.rs
Tiny PR to clear out potential confusion of generating triples of random coefficients, mentioned in #88.
I assumed that it was probably preferable to leave the triple as is, rather than handling the two cases separately.
@irakliyk let me know what you'd prefer.
closes #88.
=> Clarify use of gamma in doc

prover/src/matrix/row_matrix.rs
During transposing a column-major matrix to row-major one, prefer writing to contiguous memory locations. 
> **Note** This change brings ~2-3% performance improvement.
=> Update Matrix Transpose Logic

CHANGELOG.md, math/src/fft/concurrent.rs, math/src/fft/fft_inputs.rs, math/src/fft/mod.rs, prover/benches/row_matrix.rs, prover/src/matrix/col_matrix.rs, prover/src/matrix/mod.rs, prover/src/matrix/row_matrix.rs, prover/src/matrix/segments.rs, prover/src/matrix/tests.rs
This PR implements multi-threaded polynomial evaluation (using FFT) for `RowMatrix` struct and also refactors/improves single-threaded evaluation
Benchmarking this on Apple M1 Pro for `f64` field, 64-column matrix, and $2^{20} \rightarrow 2^{23}$ extension, I get the following results:
- Single-threaded evaluation: ~40% faster than using column-based approach.
- Multi-threaded evaluation: ~37% faster than using column-based approach.
Unfortunately, this PR also results in some code duplication. Specifically, `split_radix_fft` methods had to be duplicated for `RowMatrix` almost entirely. But overall, I think it is worth it.
=> Multi-threaded evaluation in `RowMatrix`

math/src/field/f64/mod.rs
This PR changes the "two-adic" root of unity for the `f64` field. The new root of unity has a nice property that for domains of size 64 the root of unity is 8, and thus many multiplications can be replaced with shifts for NTT computations (though, we are not taking advantage of this yet).
=> New root of unity for f64 field

air/src/proof/mod.rs, examples/src/lib.rs, examples/src/main.rs
This PR adds proven security level estimate.
Examples now show both conjectured and proven security levels.
The $m$ parameter in the proven security is updated dynamically to optimize the balance between field security and query security. The approach taken is based on the two following assumptions:
- For the "pre-FRI-query err" as mentioned in [ethSTARK paper](https://eprint.iacr.org/2021/582.pdf), only the third (dominant) component, i.e. $\dfrac{(m+\frac{1}{2})^7 \cdot n^2}{2\rho^{3/2}q}$, is considered.
- For the "FRI-query err", the value $\sqrt{\rho} \cdot (1 + \frac{1}{2m})$ is approximated by $\sqrt{\rho}$. The reason for this is that the term $\frac{1}{2m} \leq \frac{1}{6}$ is fairly small, and doubling $m$ removes about 7 bits of security for the pre-FRI-query term.
Based on …
=> Security estimate

air/src/air/tests.rs, air/src/options.rs, air/src/proof/commitments.rs, examples/src/fibonacci/fib_small/tests.rs, examples/src/fibonacci/utils.rs, examples/src/lib.rs, examples/src/merkle/tests.rs, examples/src/rescue/tests.rs, examples/src/rescue_raps/tests.rs, examples/src/vdf/exempt/tests.rs, examples/src/vdf/regular/tests.rs, fri/src/options.rs, fri/src/proof.rs, fri/src/prover/mod.rs, fri/src/verifier/channel.rs, fri/src/verifier/mod.rs, prover/src/tests/mod.rs, winterfell/src/lib.rs
This PR proposes another method for performing the final check in the FRI query stage. Specifically, in the current implementation the verifier receives a code word from the prover which the latter claims to be consistent with an honest execution of the protocol.
The verifier then checks that the commitment to the received code word matches the one received in the commit phase of the protocol. The verifier then goes on to interpolate the code word in order to find the corresponding remainder polynomial. The verifier concludes by checking whether the degree of this polynomial is less than the expected degree bound (which can be computed from the input polynomial degree bound and the protocol parameters).
The current proposal simplifies things by sending the remainder polynomial directly. …
=> Send remainder polynomial instead of remainder code word

README.md, air/src/air/mod.rs, air/src/air/trace_info.rs, air/src/options.rs, air/src/proof/context.rs, examples/src/lamport/aggregate/air.rs, examples/src/lamport/threshold/air.rs, examples/src/merkle/air.rs, examples/src/rescue/air.rs, examples/src/rescue_raps/air.rs, examples/src/vdf/exempt/air.rs, examples/src/vdf/regular/air.rs, math/src/field/mod.rs, math/src/field/traits.rs, math/src/lib.rs, prover/src/channel.rs, prover/src/lib.rs, verifier/src/lib.rs, winterfell/src/lib.rs
This PR implements reduction to elements of public inputs and proof context. This will allow `RandomCoin` to be initialized from a list of field elements (rather than bytes). The advantage of this approach is that it simplifies handling of random coin in the context of recursive proofs.
=> To element reduction of public inputs and proof context

CHANGELOG.md, air/Cargo.toml, air/src/options.rs, crypto/Cargo.toml, examples/Cargo.toml, fri/Cargo.toml, math/Cargo.toml, prover/Cargo.toml, utils/core/Cargo.toml, utils/rand/Cargo.toml, verifier/Cargo.toml, winterfell/Cargo.toml
This PR prepares for v0.6.0 release. Specifically, all crate version numbers were increased to v0.6.0 and changelog was updated.
=> Prepare v0.6.0 release

air/src/proof/mod.rs, examples/src/main.rs
The `get_proven_security` function uses both `log2` and `powf` which are both incompatible with a `no_std` environment.  To fix support for `no_std` this PR moves the `get_proven_security` function behind a `std` feature flag and panics if it is called in a `no_std` context.
=> Fix `no_std` support

CHANGELOG.md, air/Cargo.toml, crypto/Cargo.toml, examples/Cargo.toml, fri/Cargo.toml, math/Cargo.toml, prover/Cargo.toml, utils/core/Cargo.toml, utils/core/src/lib.rs, utils/rand/Cargo.toml, verifier/Cargo.toml, winterfell/Cargo.toml
This PR updates crate versions to v0.6.1 and also adds feature-based `Box` re-export to the core utils crate.
=> Prepare v0.6.1 release

crypto/src/merkle/mod.rs, prover/src/lib.rs, prover/src/matrix/col_matrix.rs, prover/src/matrix/mod.rs, prover/src/matrix/row_matrix.rs, prover/src/matrix/segments.rs
Changes:
* Make MerkleTree fields public so the merkle nodes can be generated in a custom way (on the GPU in my case)
* Add merge_column to ColMatrix to append columns
* Make get_offsets public
* Make Segment public
* remove .data() from Segment and instead implement Deref (gives access to the data Vec instead of the slice which I need to call .capacity() on)
=> MerkleTree, Segment, ColMatrix changes for GPU RPO support

prover/src/constraints/commitment.rs, prover/src/constraints/composition_poly.rs, prover/src/constraints/mod.rs, prover/src/lib.rs
Changes:
* Made CompositionPoly and ConstraintCommitment public to allow overriding build_constraint_commitment
* Removed `.evaluate` from composition poly and use RowMatrix::evaluate_polys_over instead (this is now consistent with build_trace_commitment)
* ConstraintCommitment takes a RowMatrix of evaluations instead of a ColMatrix
=> Make changes to enable custom build_constraint_commitment

fri/src/folding/mod.rs
Refactored `get_inv_offsets` for some performance improvements. Results:
=> Performance improvement for FRI

math/src/utils/mod.rs, verifier/src/composer.rs
Uses batch inverse function to save some cycles during verification.
This was derived while working on [zkDilithium](https://github.com/guruvamsi-policharla/zkdilithium) as part of [ia.cr/2023/414](https://ia.cr/2023/414).
|code| old | new| 
|--|--|--|
| rescue | 0.9 ms| 0.6 ms|
| vdf    | 2.0 ms| 1.8 ms|
| mulfib | 0.8 ms| 0.7 ms|
=> Speedup proof verification using batched inverse.

air/src/proof/ood_frame.rs, prover/src/channel.rs, verifier/src/channel.rs, verifier/src/lib.rs
This PR introduces a small optimization that compactifies the OOD frame when passed through the channels. This leads to a reduction in the number of required hashes needed for reseeding the random coin which should make a difference in the setting of recursive proofs.
=> Compactify serialization of ood frame

air/src/air/coefficients.rs, air/src/air/mod.rs, air/src/proof/mod.rs, crypto/src/random/mod.rs, prover/src/composer/mod.rs, prover/src/lib.rs, verifier/src/composer.rs
Removes the degree adjustment performed on the DEEP composition polynomial. This leads to a negligible increase in the soundness error of the protocol i.e. the $+2$ in the formula for $k^+$. The new soundness error for the current protocol is given by:
$$
L^{+}\cdot\left(\frac{1}{|\mathbb{F}|} + \frac{d\cdot(k^+ - 1) + (k-1)}{|\mathbb{F}| - |D\cup H|}\right) + \epsilon_{FRI}
$$
where:
1. $H$ is the trace domain of size $k$
2. $D$ is the LDE domain of size $n$
3. $k^+ := k + 2$
4. $L^+ := \frac{m+0.5}{\sqrt{\rho^+}}$ where $m\geq 3$ is the Johnson proximity parameter which for simiplicity can be taken to be equal to $3$ and $\rho^+ := \frac{k^+}{n}$
5. $\mathbb{F}$ is the extension field.
6. $\epsilon_{FRI}$ is the soundness error bound for FRI run with proximity parameter $\theta^+ := 1 - …
=> Simplify DEEP composition polynomial

prover/src/trace/trace_table.rs
This pull request aims to enhance the functionality of the `TraceTable` struct by implementing the `Debug` and `Clone` traits. For instance, this change would enable cloning of the local variable `trace` while usage at stages: `prove()` and `get_pub_inputs()` functions. These two stages are responsible for generating the proof and obtaining the public inputs, respectively, which are then utilized in the `verify()` function.
1. Implement the `Debug` trait for the `TraceTable` struct, allowing for easier debugging and inspection of the `TraceTable` instances.
2. Implement the `Clone` trait for the `TraceTable` struct, enabling the cloning of the local variable `trace` at the `prove()` and `get_pub_inputs()` levels.
The motivation behind this pull request is to improve the flexibility and …
=> [Feat] Added Debug, Clone traits to TraceTable

math/Cargo.toml, math/src/field/extensions/cubic.rs, math/src/field/extensions/quadratic.rs, math/src/field/f128/mod.rs, math/src/field/f62/mod.rs, math/src/field/f64/mod.rs
This adds conditional support for serde. It allow serializing/deserializing the field elements, which is useful for downstream applications, for instance, to save test data.
The change is behind a feature flag to avoid impacting compilation times.
=> feature: add conditional support for serde

crypto/src/random/default.rs, crypto/src/random/mod.rs, fri/src/prover/channel.rs, fri/src/prover/tests.rs, prover/src/channel.rs, prover/src/lib.rs, verifier/src/lib.rs
=> Refactor RandomCoin trait

examples/src/fibonacci/fib2/mod.rs, examples/src/fibonacci/fib2/prover.rs, examples/src/fibonacci/fib8/mod.rs, examples/src/fibonacci/fib8/prover.rs, examples/src/fibonacci/fib_small/mod.rs, examples/src/fibonacci/fib_small/prover.rs, examples/src/fibonacci/mulfib2/mod.rs, examples/src/fibonacci/mulfib2/prover.rs, examples/src/fibonacci/mulfib8/mod.rs, examples/src/fibonacci/mulfib8/prover.rs, examples/src/lamport/aggregate/mod.rs, examples/src/lamport/aggregate/prover.rs, examples/src/lamport/threshold/mod.rs, examples/src/lamport/threshold/prover.rs, examples/src/merkle/mod.rs, examples/src/merkle/prover.rs, examples/src/rescue/mod.rs, examples/src/rescue/prover.rs, examples/src/rescue_raps/mod.rs, examples/src/rescue_raps/prover.rs, examples/src/vdf/exempt/mod.rs, examples/src/vdf/exempt/prover.rs, examples/src/vdf/regular/mod.rs, examples/src/vdf/regular/prover.rs, prover/src/constraints/evaluator.rs, prover/src/constraints/mod.rs, prover/src/lib.rs, winterfell/src/lib.rs
=> Add ability for custom constraint evaluators

air/Cargo.toml, air/src/proof/mod.rs
Addresses #183 
This solution relies on the `fixed` crate for fixed point arithmetic. It also uses an approximation for the `log(1 + x)` function as well as other upper/lower bounds. To compensate for the pessimistic bounds in the no-std version, some `-1` subtractions after `cmp::min` were removed. Surprisingly this lead to results which are closer to the results using infinite precision integers, at least in the cases that were tested.
Still the logic seems a bit over complicated and this means that there are probably some corner cases that were overlooked.
=> Protocol proven security in no-std

examples/src/fibonacci/fib2/mod.rs, examples/src/fibonacci/fib8/mod.rs, examples/src/fibonacci/fib_small/mod.rs, examples/src/fibonacci/mulfib2/mod.rs, examples/src/fibonacci/mulfib8/mod.rs, examples/src/lamport/aggregate/mod.rs, examples/src/lamport/threshold/mod.rs, examples/src/merkle/mod.rs, examples/src/rescue/mod.rs, examples/src/rescue_raps/mod.rs, examples/src/vdf/exempt/mod.rs, examples/src/vdf/regular/mod.rs, verifier/src/errors.rs, verifier/src/lib.rs, winterfell/src/lib.rs
=> Add acceptable options argument to verification

CHANGELOG.md, air/src/proof/mod.rs, crypto/src/random/default.rs, crypto/src/random/mod.rs, prover/src/channel.rs, prover/src/lib.rs, verifier/src/channel.rs, verifier/src/lib.rs
This PR is an alternative to #220 (and as such it also addresses #216). However, the approach taken here is de-duplicate query positions explicitly at the prover and the verifier, rather than doing it implicitly during Merkle path generation.
=> Allow duplicate query positions

math/src/field/f128/mod.rs, math/src/field/f62/mod.rs, math/src/field/f64/mod.rs
Implements `Debug` by hand for the base fields such that it outputs a human-readable integer.
The current behavior makes the fields unintuitive when debugging `Vec<BaseElement>`. Specifically, `Vec` doesn't implement `Display`, so we're forced to use the `Debug` output:
```rust
let v: Vec<BaseElement> = vec![BaseElement::from(1u64)];
println!("{v:?}");
// current output: [ BaseElement(<Montgomery form of 1>) ]
// new output: [ 1 ]
```
I believe most users will be confused by the current output, and would expect to read an integer (as I was).
=> change `Debug` format for fields

air/src/options.rs, air/src/proof/commitments.rs, air/src/proof/context.rs, air/src/proof/mod.rs, air/src/proof/ood_frame.rs, air/src/proof/queries.rs, utils/core/src/serde/mod.rs
- adds size hints to some serializations
- implement serialization and deserialization traits for StarkProof (using existing code)
- add blanket implementation for integers and option type
=> Stark proof serializable deserializable

air/src/proof/tests.rs
Just adding a missing copyright header to the new file introduced in https://github.com/facebook/winterfell/pull/234
=> Adding copyright header to tests file

utils/core/src/serde/mod.rs
The `Deserializer` trait does not have an associated type, all methods return `Self`. That means it is not possible to have a blanket implementation for slices `&[T]`, because the signature is required to be `fn read_from<R: ByteReader>(source: &mut R) -> Result<&[T], DeserializationError>;`. I can't add a associated type without making a breaking change because default associated types are unstable https://github.com/rust-lang/rfcs/blob/master/text/2532-associated-type-defaults.md. I also can't define a blanket implementation for `Vec<T>` because the default serializer does not include the length of the vector.
edit: also note:
- the serializer doesn't return errors, if one decides to encode an `usize` into `u8` there is nothing to do besides panicking, this could be an attack vector.
- …
=> serde: add default deserializers implementations

air/src/proof/mod.rs
This prevents other data structure to be serialized in the same buffer, which happen naturally for structs with additional field elements.
=> bugfix: StarkProof is not always the last element in a serialization buffer

CHANGELOG.md, utils/core/Cargo.toml, utils/core/src/serde/byte_reader.rs, utils/core/src/serde/byte_writer.rs, utils/core/src/serde/mod.rs, utils/core/src/tests.rs
This PR adds [vint64](https://docs.rs/vint64/latest/vint64/) variable-length serialization and deserialization implementation for `usize` type.
=> Implement serialization and deserialization for `usize` type

air/src/proof/mod.rs
As the title says and it corrects a few minor mistakes. The security estimates do not change (when rounding to bits) after testing with some of the examples.
=> Make dependence on number of openings explicit in security estimator

examples/Cargo.toml, examples/src/fibonacci/fib2/mod.rs, examples/src/fibonacci/fib8/mod.rs, examples/src/fibonacci/fib_small/mod.rs, examples/src/fibonacci/mulfib2/air.rs, examples/src/fibonacci/mulfib2/mod.rs, examples/src/fibonacci/mulfib8/air.rs, examples/src/fibonacci/mulfib8/mod.rs, examples/src/lamport/aggregate/mod.rs, examples/src/lamport/threshold/mod.rs, examples/src/main.rs, examples/src/merkle/mod.rs, examples/src/rescue/mod.rs, examples/src/rescue_raps/mod.rs, examples/src/vdf/exempt/air.rs, examples/src/vdf/exempt/mod.rs, examples/src/vdf/regular/air.rs, examples/src/vdf/regular/mod.rs, prover/Cargo.toml, prover/src/lib.rs, prover/src/trace/trace_lde/default/mod.rs, verifier/README.md
This PR changes the logger implementation from default [log](https://crates.io/crates/log) to [Tracing](https://crates.io/crates/tracing), which allows to implement informative tree-like log.
=> Implementation of Tracing logger

air/src/options.rs, air/src/proof/context.rs, crypto/benches/merkle.rs, crypto/src/hash/griffin/griffin64_256_jive/digest.rs, crypto/src/hash/griffin/griffin64_256_jive/tests.rs, crypto/src/hash/rescue/rp64_256/digest.rs, crypto/src/hash/rescue/rp64_256/tests.rs, crypto/src/hash/rescue/rp64_256_jive/digest.rs, crypto/src/hash/rescue/rp64_256_jive/tests.rs, crypto/src/merkle/concurrent.rs, examples/src/lamport/aggregate/prover.rs, examples/src/lamport/signature.rs, examples/src/lamport/threshold/air.rs, examples/src/lamport/threshold/prover.rs, fri/src/folding/mod.rs, math/src/fft/concurrent.rs, math/src/fft/serial.rs, math/src/field/extensions/cubic.rs, math/src/field/extensions/quadratic.rs, math/src/field/f128/mod.rs, math/src/field/f128/tests.rs, math/src/field/f62/mod.rs, math/src/field/f62/tests.rs, math/src/field/f64/mod.rs, math/src/field/f64/tests.rs, math/src/field/traits.rs, math/src/polynom/tests.rs, prover/src/matrix/segments.rs
This PR addresses #230 and also does the same for `f62` and `f128` field.
Other changes in this PR:
- Cleaned up code as per clippy suggestions.
- Made some functions `const` for `f64` field.
- Added `as_int()` implementation to the `f64` field struct.
=> Remove `From` impls resulting in silent field element conversions

CHANGELOG.md, air/src/proof/commitments.rs, air/src/proof/mod.rs, air/src/proof/ood_frame.rs, air/src/proof/queries.rs, air/src/proof/table.rs, crypto/src/hash/blake/mod.rs, crypto/src/hash/sha/mod.rs, crypto/src/merkle/proofs.rs, fri/src/proof.rs, math/src/field/f128/tests.rs, utils/core/src/serde/byte_reader.rs, utils/core/src/serde/byte_writer.rs, utils/core/src/serde/mod.rs, utils/core/src/tests.rs
This PR removes current implementations of `Serializable` and `Deserilizable` traits from slices and vectors. The motivation for this is that the way sterilization worked for these structs was somewhat confusing (slices and vectors were serialized without their lengths). Instead, we can use explicit calls to `write_batch()` and `read_batch()` methods to accomplish the same thing.
In the future, we can reimplement `Serializable` and `Deserializable` on slices and vecs, but this time we would serialize them together with the number of elements (for which we can use `usize` serialization implemented in #238).
=> Remove `Serializable` and `Deserializable` implementations from slices and vecs

air/src/proof/context.rs, math/src/field/extensions/cubic.rs, math/src/field/extensions/quadratic.rs, math/src/field/f128/mod.rs, math/src/field/f62/mod.rs, math/src/field/f64/mod.rs, math/src/field/traits.rs
This small PR implements the `TryFrom<u64>` and `TryFrom<u128>` bounds for the structs which implements `FieldElement` trait, namely: 
- BaseElement(u64)
- BaseElement(u128)
- QuadExtension
- CubeExtension
=> Add `TryFrom<u64>` and `TryFrom<u128>` bounds to the `FieldElement` trait

utils/core/src/serde/byte_writer.rs, utils/core/src/serde/mod.rs
Removes the `Sized` bound, it is no longer necessary, since https://github.com/facebook/winterfell/pull/239 .
The change above allows for `impl<T: Serializable> Serializable for &T`.
The change above allows to change `write_many` to be generic and receive a `IntoIterator` without breaking the serialization for `[T; C]`
The removal of the `Sized` bound also makes the trait object save, and allows for type erasure.
=> Support into iterator

utils/core/src/serde/mod.rs
This adds a generic implementation of the traits `Serializable` and `Deserializable` for the following types:
- Vec
- BTreeMap
- BTreeSet
Unfortunately I could use `IntoIterator` because that would conflict with the existing implementation for tuples, and the issue can not be solved without [trait specialization](https://rust-lang.github.io/rfcs/1210-impl-specialization.html)
=> serde: add support for some of the alloc collections

README.md
The example outlined in the README gives an error (FRI polynomial remainder degree must be one less than a power of two).
This is caused by using wrong value of 128 for the fri_remainder_max_degree, the fri remainder has to have a number of coefficients that is power of two (therefore polynomial degree has to be one less than that) so value 127 works well.
=> Change fri remainder max degree to 127 for the example

air/src/proof/mod.rs, air/src/proof/ood_frame.rs, prover/src/channel.rs, prover/src/composer/mod.rs, prover/src/trace/poly_table.rs, verifier/src/channel.rs, verifier/src/lib.rs
Applies https://github.com/facebook/winterfell/pull/247#discussion_r1537123827
=> Refactor `TraceOodFrame`

math/src/field/f64/mod.rs
This adds the following conversions to the 64 bit field:
- `impl From<bool> for BaseElement`
- `TryFrom<BaseElement> for u32`
- `TryFrom<BaseElement> for u16`
- `TryFrom<BaseElement> for u8`
- `TryFrom<BaseElement> for bool`
=> f64: additional conversions

.github/workflows/ci.yml, prover/benches/lagrange_kernel.rs, prover/src/trace/trace_lde/default/tests.rs, utils/core/src/serde/byte_reader.rs, winterfell/src/tests.rs
- [`actions-rs/toolchain`](https://github.com/actions-rs/toolchain) is no longer maintained and it is now an archived project
- there is no official action for rust, but now the GH action image include rustup natively, so the changes bellow uses rustup directly (this is the strategy from projects like [`rust-analyzer`](https://github.com/rust-lang/rust-analyzer/blob/99718d0c8bc5aadd993acdcabc1778fc7b5cc572/.github/workflows/ci.yaml#L63-L67))
- the main change here is adding the `cargo-hack` tool. Using that tool mainly because it is recommended in the [cargo book](https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-rust-version)
- This is basically a wrapper around `cargo check`, which checks every combination of features. It is fast enough that it should be done …
=> CI: check msrv

math/src/field/f64/mod.rs
This commit also:
- Reorders conversion definitions so that integer types are in
increasing order
- Changes the conversions to use `.into()` instead of `as` casts, when
the conversion is infallible. Instead of the cast like `as u128` which
at first sight doesn't guarantee no truncation
=> felt u64: add conversion to/from usize

air/src/air/aux.rs, air/src/air/lagrange/mod.rs, air/src/air/mod.rs, air/src/lib.rs, examples/src/rescue_raps/air.rs, prover/benches/lagrange_kernel.rs, prover/src/constraints/evaluator/boundary.rs, prover/src/constraints/evaluator/default.rs, prover/src/lib.rs, prover/src/trace/mod.rs, utils/core/src/serde/mod.rs, verifier/src/evaluator.rs, verifier/src/lib.rs, winterfell/src/tests.rs
Closes #286 
I opted to expand the scope of the current `Air::evaluate_aux_transition()` and `Air::get_aux_assertions()` instead of creating new methods (as suggested in the issue), since it ended up being much cleaner.
=> Fix GKR-LogUp API

air/src/proof/ood_frame.rs, crypto/src/merkle/concurrent.rs, examples/src/utils/rescue.rs, math/src/field/f64/mod.rs, utils/core/src/serde/byte_reader.rs
This commit fixes a bug that is present in the implementation of `ByteReader::read_slice` for ReadAdapter. Specifically, it does not consume any input, so calling `read_slice` and then attempting to read the next value in the input, will read the same bytes again. The documented behavior of this function is that any of the `read_*` methods consume the corresponding amount of input.
To catch this, and to prevent future regressions, a new test was added that serializes some data to a file using one approach, and deserializes it using the ReadAdapter. This ensures that we don't accidentally make choices in the writer that aren't matched by the reader, and vice versa.
Closes #308
=> fix: incorrect read_slice impl for ReadAdapter

prover/src/constraints/evaluation_table.rs
Same as #305 
This PR relaxes the constraint degree checks so that they become degree bounds checks instead of degree equality checks.
=> Update constraint degree checks

prover/Cargo.toml, prover/benches/logup_gkr.rs, sumcheck/Cargo.toml, sumcheck/benches/bind_variable.rs, sumcheck/benches/eq_function.rs
Adds a simple end-to-end LogUp-GKR benchmark. Simplifies some of the benchmarks in the `sum-check` crate.
=> Add LogUp-GKR benchmark

air/src/air/logup_gkr/lagrange/boundary.rs, air/src/air/logup_gkr/lagrange/frame.rs, air/src/air/logup_gkr/lagrange/transition.rs, air/src/proof/ood_frame.rs, prover/benches/logup_gkr.rs, prover/src/constraints/evaluation_table.rs, prover/src/constraints/evaluator/default.rs, prover/src/constraints/evaluator/logup_gkr.rs, prover/src/constraints/evaluator/logup_gkr_evaluator.rs, prover/src/constraints/evaluator/mod.rs, prover/src/constraints/mod.rs, prover/src/lib.rs, prover/src/logup_gkr/mod.rs, prover/src/trace/mod.rs, prover/src/trace/trace_lde/default/mod.rs, winterfell/src/lib.rs, winterfell/src/tests/logup_gkr_periodic.rs, winterfell/src/tests/logup_gkr_simple.rs
Builds on #315 and supersedes #316 .
The PR proposes a new constraint evaluator that is specific to when LogUp-GKR is enabled.
This has also the advantage of closing #306 .
=> Parallelize Lagrange constraints evaluation

sumcheck/benches/bind_variable.rs, sumcheck/src/multilinear.rs
This PR removes the slide bound checks in `MultiLinearPoly::bind_least_significant_variable`.
In the serial case, we see a 7-9% improvement in the `bind-variable` benchmark, and sum-check performance improvement by 2.5-3.5%. Parallel performance doesn't change, presumably since the algorithm is bounded by the threading overhead rather than the time each threads spends looping over its chunk.
The LogUp-GKR benchmark also didn't change, since `bind_least_significant_variable` was not a bottleneck. However I see this PR as a proof of concept, and will apply similar bound checks removal in any hot loop I find in a subsequent PR.
Below are the serial bind-variable and sum-check benchmark results:
```
bind variable //262144  time:   [219.29 µs 225.73 µs 231.25 µs]
change: [-9.5833% -6.9170% …
```
=> Optimize `bind_least_significant_variable`

prover/Cargo.toml, prover/src/logup_gkr/mod.rs, utils/core/src/iterators.rs, winterfell/src/tests/logup_gkr_periodic.rs
Leads to about to 20-25% improvement in input layer generation.
=> Parallelize input layer generation

README.md, winterfell/src/lib.rs
PR fixes a minor issue in the documentation of the default prover/verifier example - note the cargo build is independent of this problem. 
The [prover example](https://docs.rs/winterfell/latest/winterfell/) causes rust analyser (vs code) to flag an error - requiring a ref to be added here `E::from(42u32)` - adding the ref causes the analyser to flag another error asking for the ref to be removed.
```
let current_state = &frame.current()[0];
let next_state = current_state.exp(3u32.into()) + E::from(42u32); 
```
Removing the ref in the first line solves the problem.
=> Minor: Documentation of the default prover/verifier example causes issue in rust analyser

math/src/field/f128/mod.rs, math/src/field/f62/mod.rs, math/src/field/f64/mod.rs, utils/core/src/serde/byte_writer.rs, utils/core/src/serde/mod.rs, utils/core/src/tests.rs
Implements `get_size_hint` for the types that are implemented by default.
Currently, crates that call `u8.get_size_hint()` get the default value of 0 which makes it harder to implement `get_size_hint` for custom types, since they cannot simply call `get_size_hint` on the contained types recursively. This PR fixes that.
This change is non-breaking.
See also https://github.com/0xPolygonMiden/miden-base/pull/895#pullrequestreview-2326556758 for more context.
=> feat(utils): Implement `get_size_hint` for default impls

prover/src/logup_gkr/prover.rs, sumcheck/benches/sum_check_plain.rs, sumcheck/src/lib.rs, sumcheck/src/prover/high_degree.rs, sumcheck/src/prover/mod.rs, sumcheck/src/prover/plain.rs, sumcheck/src/univariate.rs
Implements the optimization in Section 3.3 [here](https://eprint.iacr.org/2024/108).
Benchmarks show about 20% improvement in sum-check proving times.
=> Reduce degree of sum-check round polynomials

CHANGELOG.md, air/src/air/context.rs, air/src/proof/ood_frame.rs, air/src/proof/table.rs, crypto/src/hash/mds/mds_f64_12x12.rs, crypto/src/hash/mds/mds_f64_8x8.rs, crypto/src/merkle/concurrent.rs, examples/src/utils/rescue.rs, math/src/field/extensions/cubic.rs, math/src/field/extensions/quadratic.rs, math/src/field/f128/mod.rs, math/src/field/f62/mod.rs, math/src/field/f64/mod.rs, prover/src/channel.rs, prover/src/constraints/evaluation_table.rs, prover/src/constraints/evaluator/default.rs, prover/src/matrix/col_matrix.rs, prover/src/trace/trace_table.rs, utils/core/src/serde/byte_reader.rs, utils/maybe_async/README.md, utils/maybe_async/src/lib.rs
Adds `maybe_async_trait` which adds a way to use `async_trait` based on whether the `async` feature is turned on. The attribute needs to be set for the trait impl and definition blocks. The macro takes functions annotated with `#[maybe_async]`, makes them async, and then sets `#[async_trait]`.
One small consequence of this is that when you have code like this:
```rust
use winter_maybe_async::{maybe_async_trait, maybe_async}
#[maybe_async_trait]
pub trait Example {
#[maybe_async]
pub fn foo() { }
}
```
If you turn on the `async` feature, then `maybe_async` becomes an unused import (because `maybe_async_trait` essentially removes it from `foo`) which might affect clippy lints. One way to deal with this would be to import macros like this: `use winter_maybe_async::*`.
=> feat: Add `maybe_async_trait`

README.md, air/src/options.rs, prover/Cargo.toml, prover/src/lib.rs, prover/src/matrix/row_matrix.rs, verifier/src/channel.rs
This is a small fix for the condition under which partitioned hashing when committing is enabled.
=> Fix partition hashing

CHANGELOG.md, air/src/errors.rs, crypto/src/errors.rs, fri/src/errors.rs, prover/src/errors.rs, utils/core/src/errors.rs, utils/core/src/serde/mod.rs, verifier/src/errors.rs
Implements `core::error::Error` for all error types in a non-breaking way, which is why this targets `main`.
The motivation is to be able to wrap these errors in `Box<dyn Error>` and use them as `source` errors which requires the trait to be implemented. 
Also fixes a clippy lint introduced in a recent rust nightly version replacing `string.as_bytes().len()` with `string.len()`.
=> Implement `core::error::Error` for all error types

air/src/options.rs, prover/src/lib.rs, prover/src/matrix/row_matrix.rs, prover/src/trace/trace_lde/default/mod.rs, verifier/src/channel.rs
This simplifies partition calculations, fixes the wrong buffer size for merging partitions, and provides accessor methods for GPU to determine correct partition sizes.
`min_partition_size` is replaced by `hash_rate` - how many base elements are consumed by one hash iteration. This allows us to calculate at which point it makes sense to start a new partition. `min_partition_size = hash_rate / E::EXTENSION_DEGREE`.
Supersedes https://github.com/facebook/winterfell/pull/339
=> Multi GPU partition fixes

fri/README.md, math/README.md
Hey !
I fixed several spelling issues.Glad I could help .
Br, Guayaba221.
=> docs fix spelling issues

air/src/proof/mod.rs, air/src/proof/security.rs
Updates the estimator to take into account the method of batching used in computing the DEEP polynomial.
Note also:
- I have updated the error term $\epsilon_3$ as this was missed in the previous PR which updated the error of the protocol to be the round-by-round error.
- I have updated the conjectured security formula to match exactly the one given in the ethSTARK paper. Moreover, and as far as I can see, the formula is independent of the type of batching used and hence the security estimator for conjectured security is unaffected.
=> Update security estimator to take into account method of batching

air/src/air/coefficients.rs, air/src/air/mod.rs, air/src/options.rs, air/src/proof/mod.rs, air/src/proof/ood_frame.rs, air/src/proof/security.rs, examples/src/fibonacci/mulfib2/mod.rs, examples/src/fibonacci/mulfib8/mod.rs, examples/src/main.rs, examples/src/rescue_raps/tests.rs, math/src/field/f128/mod.rs, math/src/field/f62/mod.rs, math/src/field/f64/mod.rs, prover/src/channel.rs, prover/src/composer/mod.rs, prover/src/constraints/composition_poly.rs, prover/src/lib.rs, utils/core/src/serde/mod.rs, verifier/src/channel.rs, verifier/src/composer.rs, verifier/src/lib.rs
This leads to a simplification of the code and has a also a simplifying effect on recursive verification.
Note: Ran some benchmarks and it seems that there is no noticeable performance changes.
=> Open quotient polynomials at `gz`

air/src/air/coefficients.rs
This PR refactors the code that draws composition coefficient for random linear combinations to make the code a bit more uniform and easier to follow.
=> Simplify drawing of composition coefficients

air/src/proof/mod.rs, air/src/proof/ood_frame.rs, prover/src/channel.rs, prover/src/lib.rs, verifier/src/lib.rs
Merges the OOD evaluations of the trace and constraints composition polynomials into one vector which is absorbed into the transcript in one-go.
=> Absorb OOD evaluations only once into the transcript
