facebook/winterfell

examples/README.md, examples/src/lamport/mod.rs, examples/src/lamport/threshold/air.rs, examples/src/lamport/threshold/mod.rs, examples/src/lamport/threshold/signature.rs, examples/src/lamport/threshold/trace.rs, examples/src/lib.rs, examples/src/main.rs
This PR will implement threshold version of LamportPlus signature aggregation.
=> Threshold lamport example

examples/src/main.rs, fri/benches/folding.rs, fri/src/verifier/mod.rs, math/src/polynom/mod.rs, math/src/polynom/tests.rs
This PR implements support for multiple folding factors (currently limited to 4, 8, 16) in FRI verifier. Right now, this doesn't have any effect because the folding factor in the prover is hard-coded to 4, but this PR will help with implementing #10
=> Generic FRI verifier

README.md, air/Cargo.toml, crypto/Cargo.toml, examples/Cargo.toml, fri/Cargo.toml, math/Cargo.toml, prover/Cargo.toml, utils/core/Cargo.toml, utils/rand/Cargo.toml, verifier/Cargo.toml, winterfell/Cargo.toml
This PR prepares the repo for v0.3 release of the library.
=> Preparation for v0.3 release

math/src/field/f64/mod.rs
This PR improves inversion in the `f64` field by replacing the current implementation with the method based on Fermat’s little theorem. Specifically, we fully unroll the multiplication by `M - 2` which allows us to achieve modular in version in 72 multiplications.
The net result is that this implementation is about 2.5x faster than the previous one.
=> Improve inversion in f64 field

air/src/air/boundary/constraint_group.rs, air/src/air/boundary/mod.rs, air/src/air/context.rs, air/src/air/mod.rs, air/src/air/trace_info.rs, prover/src/constraints/boundary.rs, prover/src/constraints/evaluator.rs, prover/src/trace/commitment.rs, utils/core/src/lib.rs, utils/rand/src/lib.rs, verifier/src/lib.rs, winterfell/src/lib.rs
This PR implements `Randomizable` trait for `u8`, `u16` and `u32` values.
=> More randomizable values

README.md, air/README.md, air/src/air/mod.rs, air/src/air/trace_info.rs
This PR adds a few missing pieces for documenting Randomized AIR.
=> RAP documentation

fri/src/lib.rs
One line visibility change to support usage of hashes in our Fractal implementation.
=> Changed visability of fri utils

fri/src/options.rs, fri/src/prover/mod.rs, fri/src/prover/tests.rs, fri/src/verifier/mod.rs
This PR extends the FRI protocol to cover the minimal possible folding factor i.e. 2.
=> Fri extended to folding factor 2

fri/src/errors.rs, fri/src/prover/mod.rs, fri/src/verifier/channel.rs, prover/src/constraints/evaluator.rs
This PR proposes a solution to point 1 in #126 .
=> More efficient remainder commitment

air/src/proof/table.rs, examples/src/vdf/mod.rs, math/src/fft/fft_inputs.rs, prover/src/matrix.rs
Very tiny PR, some files were missing the copyright + MIT license mention.
=> Add missing license mention

.github/workflows/ci.yml, CHANGELOG.md, air/Cargo.toml, crypto/Cargo.toml, examples/Cargo.toml, fri/Cargo.toml, math/Cargo.toml, math/src/field/f128/tests.rs, prover/Cargo.toml, utils/core/Cargo.toml, utils/core/src/serde/byte_reader.rs, utils/rand/Cargo.toml, verifier/Cargo.toml, winterfell/Cargo.toml
=> Fix no-std build for winter-utils

CHANGELOG.md, air/src/air/coefficients.rs, air/src/air/mod.rs, crypto/src/random/mod.rs, prover/src/composer/mod.rs, prover/src/lib.rs, verifier/src/composer.rs
Following the remark [here](https://twitter.com/EliBenSasson/status/1625140730736828416) the present PR proposes a simplification in the way the deep composition polynomial is computed.
=> Remove conjugate term in deep composition polynomial

CHANGELOG.md, crypto/src/hash/griffin/griffin64_256_jive/mod.rs, crypto/src/hash/rescue/rp62_248/mod.rs, crypto/src/hash/rescue/rp64_256/mod.rs, crypto/src/hash/rescue/rp64_256_jive/mod.rs, math/src/field/extensions/cubic.rs, math/src/field/extensions/quadratic.rs, math/src/field/f128/mod.rs, math/src/field/f62/mod.rs, math/src/field/f64/mod.rs, math/src/field/traits.rs
This PR adds a couple of methods to simplify conversions between base and extension field elements.
=> Conversions between base and extension field elements

air/src/air/tests.rs, air/src/options.rs, examples/benches/fibonacci.rs, examples/benches/rescue.rs, examples/src/fibonacci/fib_small/tests.rs, examples/src/fibonacci/utils.rs, examples/src/lib.rs, examples/src/merkle/tests.rs, examples/src/rescue/tests.rs, examples/src/rescue_raps/tests.rs, examples/src/vdf/exempt/tests.rs, examples/src/vdf/regular/tests.rs, fri/benches/prover.rs, fri/src/options.rs, fri/src/prover/tests.rs, prover/src/tests/mod.rs, winterfell/src/lib.rs
This PR does minor refactoring of FRI and proof options structs to store max remainder degree and increase limits for some parameters.
=> FRI options cleanup

air/src/air/boundary/constraint.rs, air/src/air/boundary/constraint_group.rs, air/src/air/boundary/mod.rs, air/src/air/boundary/tests.rs, air/src/air/coefficients.rs, air/src/air/context.rs, air/src/air/mod.rs, air/src/air/tests.rs, air/src/air/transition/mod.rs, air/src/lib.rs, prover/src/composer/mod.rs, prover/src/constraints/boundary.rs, prover/src/constraints/composition_poly.rs, prover/src/constraints/evaluation_table.rs, prover/src/constraints/evaluator.rs, prover/src/lib.rs, verifier/src/channel.rs, verifier/src/composer.rs, verifier/src/evaluator.rs, verifier/src/lib.rs, winterfell/src/lib.rs
=> Simplify constraint composition by removing adjustment factors

air/src/air/context.rs, air/src/proof/context.rs
accomodate->accommodate
layed->laid
=> chore: fix typos

prover/src/lib.rs
This small PR fixes the time calculation of auxiliary trace building.
=> Update logging of auxiliary trace building

utils/core/src/serde/mod.rs
=> serde: add impl for String

.github/workflows/ci.yml, Cargo.toml, air/src/air/mod.rs, prover/Cargo.toml, prover/src/constraints/evaluator/default.rs, prover/src/lib.rs, utils/maybe_async/Cargo.toml, utils/maybe_async/README.md, utils/maybe_async/src/lib.rs, utils/maybe_async/src/parse.rs, utils/maybe_async/src/visit.rs, winterfell/Cargo.toml
Adds a `maybe_async` proc macro, and uses it to expose an async version of the `Prover` trait
=> Introduce async `Prover`

air/src/air/context.rs, air/src/air/trace_info.rs, winterfell/src/tests/logup_gkr_periodic.rs, winterfell/src/tests/logup_gkr_simple.rs
Proposes a minor cleanup of AirContext methods
=> Cleanup AirContext

examples/README.md
Hey! I fixed a significant typo, and I’ll be very glad if it helps you. Thank you for your work!
=> Fix significant typo in documentation

README.md
Fixed broken links:
Vitalik Buterin's blog series on zk-STARKs:
* [STARKs, part 1: Proofs with Polynomials](https://vitalik.ca/general/2017/11/09/starks_part_1.html)
* [STARKs, part 2: Thank Goodness it's FRI-day](https://vitalik.ca/general/2017/11/22/starks_part_2.html)
* [STARKs, part 3: Into the Weeds](https://vitalik.ca/general/2018/07/21/starks_part_3.html)
to
Vitalik Buterin's blog series on zk-STARKs:
* [STARKs, part 1: Proofs with Polynomials](https://vitalik.eth.limo/general/2017/11/09/starks_part_1.html)
* [STARKs, part 2: Thank Goodness it's FRI-day](https://vitalik.eth.limo/general/2017/11/22/starks_part_2.html)
* [STARKs, part 3: Into the Weeds](https://vitalik.eth.limo/general/2018/07/21/starks_part_3.html)
=> fix: broken links README.md

CHANGELOG.md, air/src/air/coefficients.rs, air/src/air/mod.rs, air/src/air/tests.rs, air/src/options.rs, air/src/proof/context.rs, air/src/proof/mod.rs, air/src/proof/security.rs, examples/benches/fibonacci.rs, examples/benches/rescue.rs, examples/src/fibonacci/utils.rs, examples/src/lib.rs, examples/src/merkle/tests.rs, examples/src/rescue/tests.rs, examples/src/rescue_raps/tests.rs, examples/src/vdf/exempt/tests.rs, examples/src/vdf/regular/tests.rs, prover/src/channel.rs, prover/src/tests/mod.rs, winterfell/src/lib.rs
=> Add option for algebraic/curve batching for constraint composition polynomial

CHANGELOG.md, fri/src/prover/mod.rs, fri/src/verifier/channel.rs, fri/src/verifier/mod.rs
This PR changes the way we commit to the FRI remainder polynomial i.e., we commit to its coefficients in reverse order.
=> Reverse remainder commitment

air/src/air/coefficients.rs, air/src/air/mod.rs, air/src/options.rs, air/src/proof/security.rs, examples/src/fibonacci/mulfib2/mod.rs, examples/src/fibonacci/mulfib8/mod.rs, examples/src/main.rs, examples/src/rescue_raps/tests.rs, math/src/field/f128/mod.rs, math/src/field/f62/mod.rs, math/src/field/f64/mod.rs, utils/core/src/serde/mod.rs
Adds the option the use algebraic batching optimized for Horner evaluation.
=> Add Horner-type batching
